<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Configuration is ready from Excel file]]>
    </line>
    <line>
      <![CDATA[Configuration is ready to generate HTML reports]]>
    </line>
    <line>
      <![CDATA[Configuration setup is OK]]>
    </line>
    <line>
      <![CDATA[Trying to initiate browser and loding URL]]>
    </line>
    <line>
      <![CDATA[Browser and URL is up and running]]>
    </line>
    <line>
      <![CDATA[Trying to capture screenshot on fail]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="7606" started-at="2021-05-09T07:30:34Z" finished-at="2021-05-09T07:30:41Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="7606" started-at="2021-05-09T07:30:34Z" finished-at="2021-05-09T07:30:41Z">
      <class name="com.LTM.testcases.MyTestCase1">
        <test-method status="PASS" signature="dataProvider()[pri:0, instance:com.LTM.testcases.MyTestCase1@1d057a39]" name="dataProvider" is-config="true" duration-ms="1394" started-at="2021-05-09T13:00:32Z" finished-at="2021-05-09T13:00:34Z">
          <reporter-output>
            <line>
              <![CDATA[Configuration is ready from Excel file]]>
            </line>
            <line>
              <![CDATA[Configuration is ready to generate HTML reports]]>
            </line>
            <line>
              <![CDATA[Configuration setup is OK]]>
            </line>
          </reporter-output>
        </test-method> <!-- dataProvider -->
        <test-method status="PASS" signature="setupBrowser()[pri:0, instance:com.LTM.testcases.MyTestCase1@1d057a39]" name="setupBrowser" is-config="true" duration-ms="7226" started-at="2021-05-09T13:00:34Z" finished-at="2021-05-09T13:00:41Z">
          <reporter-output>
            <line>
              <![CDATA[Trying to initiate browser and loding URL]]>
            </line>
            <line>
              <![CDATA[Browser and URL is up and running]]>
            </line>
          </reporter-output>
        </test-method> <!-- setupBrowser -->
        <test-method status="FAIL" signature="Login()[pri:0, instance:com.LTM.testcases.MyTestCase1@1d057a39]" name="Login" duration-ms="10" started-at="2021-05-09T13:00:41Z" finished-at="2021-05-09T13:00:41Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.LTM.testcases.MyTestCase1.Login(MyTestCase1.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="FAIL" signature="screenshotOnFail(org.testng.ITestResult)[pri:0, instance:com.LTM.testcases.MyTestCase1@1d057a39]" name="screenshotOnFail" is-config="true" duration-ms="323" started-at="2021-05-09T13:00:41Z" finished-at="2021-05-09T13:00:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Login status=FAILURE method=MyTestCase1.Login()[pri:0, instance:com.LTM.testcases.MyTestCase1@1d057a39] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.LTM.utility.BaseClass.screenshotOnFail(BaseClass.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:723)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[Trying to capture screenshot on fail]]>
            </line>
          </reporter-output>
        </test-method> <!-- screenshotOnFail -->
        <test-method status="SKIP" signature="tearDown()[pri:0, instance:com.LTM.testcases.MyTestCase1@1d057a39]" name="tearDown" is-config="true" duration-ms="0" started-at="2021-05-09T13:00:41Z" finished-at="2021-05-09T13:00:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.LTM.testcases.MyTestCase1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
